# Generated by Django 4.0.6 on 2022-12-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta_analisis',
            name='subz',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
